#!/usr/bin/env ruby
require 'fileutils'

module System
    def sh(command)
        return system "sh -c \"#{command}\""
    end
    def pwd
        FileUtils.pwd
    end
    def home
        File.expand_path('~')
    end
end
include System

def directory
    return  '~'
end

def install
    puts System.home
end

def update
end

def compile
end

send ARGV[0]
