#!/usr/bin/env ruby
require 'fileutils'
require './utils/System'

def install
    unless System.universe
        File.symlink(System.pwd, System.sym)
    end
    compile
end

def update
    system "#{System.universe}/utils/update-modules"
    compile
end

def compile
end

send ARGV[0]
