#!/usr/bin/env ruby
require 'fileutils'
@universe = $0.chomp('/utils/universe')
require "#{@universe}/utils/Compile"

def update
    system "#{@universe}/utils/update-modules"
    compile
end

def compile
    FileUtils.rm_rf "#{@universe}/bin"
    FileUtils.mkdir "#{@universe}/bin"
    FileUtils.symlink('../universe', "#{@universe}/bin/", force: true)
    for dir in Dir.glob("#{@universe}/sources/*").select {|f| File.directory? f}
        Compile.all File.basename dir
    end
end

send ARGV[0]
