#!/bin/bash
if [ ! -e $1 ]
then
    echo 'Path not found'
    exit 1
fi
echo 'Updating repositories'
currentPath=$PWD
cd $1
git submodule init
git submodule update --recursive
git submodule foreach 'git checkout master; git pull;'
cd $currentPath
